/** Libellés arabes des statistiques, tels qu'affichés à l'écran. */
export const STATS_LABELS = {
  screenTitle: "الإحصائيات",
  seasonsRegular: "المواسم العادية",
  seasonsSummer: "المدارس الصيفية",
  compareTitle: "مقارنة المواسم",
  typeRegularShort: "عادية",
  typeSummerShort: "صيفية",
  seasonRegular: "موسم عادي",
  seasonSummer: "مدرسة صيفية",
  active: "جاري",
  closed: "مغلق",
  activeMark: "(جاري)",
  seasonFallback: "موسم",
  loading: "جاري تحميل الإحصائيات…",
  loadError: "تعذر تحميل الإحصائيات",
  retry: "إعادة المحاولة",
  noSeasonsOfType: "لا توجد مواسم من هذا النوع",
  noSavedStats: "لا توجد إحصائيات محفوظة لهذا الموسم",
  unavailable: "غير متوفر لهذا الموسم",
  compareNotEnough: "لا توجد مواسم كافية للمقارنة",
  exportFailed: "تعذر إنشاء الملف، حاول مرة أخرى",
  exportDialog: "تصدير الإحصائيات",
  sharingUnavailable: "المشاركة غير متاحة على هذا الجهاز",
  exportFab: "export pdf",

  members: "الأعضاء",
  presenceRate: "نسبة الحضور",
  gainSeasonAvg: "متوسط الحفظ هذا الموسم",
  testsAverage: "معدل الاختبارات",
  objectifsRate: "نسبة الأعضاء الذين حققوا أهدافهم",
  seances: "الحصص",
  unitHizb: "حزب",
  unitPercent: "%",
  unitScore: "/20",
  memberSuffix: " عضو",

  total: "المجموع",
  male: "ذكور",
  female: "إناث",
  unspecified: "غير محدد",
  membersWord: "أعضاء",
  newMembers: "أعضاء جدد",
  renewals: "تجديدات",
  requestsReceived: "طلبات مستلمة",
  requestsAccepted: "طلبات مقبولة",
  requestsRejected: "طلبات مرفوضة",
  requestsPending: " طلبات قيد الانتظار",
  acceptanceRate: "نسبة القبول للطلبات",

  presence: "الحضور",
  presenceRateFact: "  نسبة الحضور",
  daysCount: "عدد الأيام",
  present: " الحضور ",
  absent: " الغياب  ",
  presenceCurve: "  تطور نسبة الحضور خلال الشهور ",
  presenceDistribution: "توزيع الأعضاء حسب نسبة الحضور ",
  band90: "90% فأكثر",
  band75: "75–90%",
  band50: "50–75%",
  bandUnder50: "أقل من 50%",
  bandNoData: "بدون بيانات",

  progress: "التقدم",
  rattrapageNote: "بيانات التقدم أعيد حسابها من سجل الحفظ",
  positionEnd: "الموقع في نهاية الموسم",
  avgQuran: "متوسط المحفوظ من القرآن",
  gainDuringSeason: "مقدار الحفظ خلال الموسم",
  gainNew: "متوسط الحفظ  الجديد",
  gainTotal: "  الأحزاب المكتمل حفظها في المجموع",
  khatmCount: "عدد الختمات",
  membersWithProgress: "عدد الأعضاء المسجَّل تقدّمهم",
  progressCurve: "تطور متوسط الحفظ حسب الشهر ",
  juzDistribution: "توزيع الأعضاء حسب المحفوظ (بالأجزاء)",
  positionHint: "(≈ {value} حزب من 60)",
  juz0_5: "0–5 أجزاء",
  juz5_10: "5–10",
  juz10_15: "10–15",
  juz15_20: "15–20",
  juz20_25: "20–25",
  juz25_30: "25–30",

  tests: "الاختبارات",
  testsCount: "عدد الاختبارات",
  invited: "المدعوون",
  graded: "المقيَّمون",
  averageOutOf20: "المعدل /20",
  minOutOf20: "الأدنى /20",
  maxOutOf20: "الأعلى /20",
  gradesDistribution: "توزيع النقاط ",
  testFallback: "اختبار",
  invitedShort: "مدعوون",
  gradedShort: "مقيَّمون",
  averageShort: "المعدل",

  objectifs: "الأهداف",
  objectifsFixed: "أهداف محددة",
  objectifsAchieved: "أهداف محققة",
  objectifsAvg: "متوسط إنجاز الأهداف",

  seanceHeadcount: "عدد الأعضاء في كل حصة",
  noSeances: "لا حصص",
  supervisors: "المشرفون",

  comparePresence: "الحضور %",
  compareGain: "متوسط الحفظ",
  compareTests: "معدل الاختبارات /20",
  compareObjectifs: "تحقيق الأهداف",
  seasonColumn: "الموسم",

  historyTitle: "سجل المواسم",
  historyLoadError: "تعذر تحميل السجل",
  historyEmpty: "لا يوجد سجل مواسم لهذا العضو",
  progressOnly: "بيانات التقدم فقط",
  from: "من",
  to: "إلى",
  tumun: "الثمن",
  gainHistory: "حفظ خلال الموسم",
  seance: "الحصة",
  supervisor: "المشرف",
  goal: "الهدف",
  achievedMark: "مُحقَّق",
  notAchievedMark: "غير مُحقَّق",

  appName: "مهندس حامل لكتاب الله",
  seasonReportTitle: "تقرير إحصائيات الموسم",
  exportDate: "تاريخ التصدير",
  memberList: "قائمة الأعضاء",
  noMemberData: "لا توجد بيانات للأعضاء",
  colName: "الاسم",
  colPosition: "الموقع",
  colGain: "الحفظ خلال الموسم",
  achieved: "محقق",
  notAchieved: "غير محقق",
  seasonCount: "عدد المواسم",
  memberUnit: "عضو",
  listSeparator: "، ",
};
